import { FlashMemoryMap } from '../types/flash';

export class CodeGenerators {
  /**
   * Generate production C Header file: tcon_flash_map.h
   */
  static generateCHeader(map: FlashMemoryMap): string {
    const timestamp = new Date().toISOString();
    const sorted = [...map.segments].sort((a, b) => a.startAddress - b.startAddress);

    const macroDefinitions = sorted.map(seg => {
      const prefix = `FLASH_${seg.name.toUpperCase().replace(/[^A-Z0-9_]/g, '_')}`;
      const endAddr = seg.startAddress + seg.size - 1;
      const sectorIdx = Math.floor(seg.startAddress / (map.sectorSize || 4096));
      return `/* ${seg.name} (${seg.description || seg.type}) */
#define ${prefix}_START_ADDR       (0x${(seg.startAddress >>> 0).toString(16).toUpperCase().padStart(8, '0')}UL)
#define ${prefix}_END_ADDR         (0x${(endAddr >>> 0).toString(16).toUpperCase().padStart(8, '0')}UL)
#define ${prefix}_SIZE             (0x${(seg.size >>> 0).toString(16).toUpperCase().padStart(8, '0')}UL) /* ${seg.size} Bytes */
#define ${prefix}_SECTOR_INDEX     (${sectorIdx})
#define ${prefix}_ACCESS           ("${seg.access}")`;
    }).join('\n\n');

    const enumEntries = sorted.map(seg => {
      const id = `FLASH_SEG_${seg.name.toUpperCase().replace(/[^A-Z0-9_]/g, '_')}`;
      return `    ${id},`;
    }).join('\n');

    const tableEntries = sorted.map(seg => {
      const endAddr = seg.startAddress + seg.size - 1;
      return `    { "${seg.name}", 0x${seg.startAddress.toString(16).toUpperCase().padStart(8, '0')}UL, 0x${endAddr.toString(16).toUpperCase().padStart(8, '0')}UL, ${seg.size}UL, "${seg.access}" },`;
    }).join('\n');

    return `/**
 * ============================================================================
 * @file    tcon_flash_map.h
 * @brief   Auto-generated Flash Memory Map Header for TCON ARM Cortex-M0
 * @chip    ${map.chipName} (${map.chipFamily})
 * @size    ${map.totalCapacity} Bytes (${map.totalCapacity / 1024} KB)
 * @date    ${timestamp}
 * @note    GENERATED BY TLiFlashManager - DO NOT EDIT MANUALLY
 * ============================================================================
 */

#ifndef TCON_FLASH_MAP_H
#define TCON_FLASH_MAP_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Total Flash Characteristics */
#define TCON_FLASH_TOTAL_CAPACITY   (0x${map.totalCapacity.toString(16).toUpperCase().padStart(8, '0')}UL)
#define TCON_FLASH_SECTOR_SIZE      (0x${(map.sectorSize || 4096).toString(16).toUpperCase().padStart(8, '0')}UL)
#define TCON_FLASH_BLOCK_SIZE       (0x${(map.blockSize || 65536).toString(16).toUpperCase().padStart(8, '0')}UL)
#define TCON_FLASH_DEFAULT_PADDING  (0x${(map.defaultPadding || 0xFF).toString(16).toUpperCase()})

/* ============================================================================
 * Segment Address & Size Definitions
 * ============================================================================ */
${macroDefinitions}

/* ============================================================================
 * Segment Enum Identifiers
 * ============================================================================ */
typedef enum {
${enumEntries}
    FLASH_SEG_COUNT
} tcon_flash_segment_id_t;

/* ============================================================================
 * Memory Segment Descriptor Structure
 * ============================================================================ */
typedef struct {
    const char *name;
    uint32_t start_addr;
    uint32_t end_addr;
    uint32_t size_bytes;
    const char *access;
} tcon_flash_segment_desc_t;

static const tcon_flash_segment_desc_t g_tcon_flash_segments[FLASH_SEG_COUNT] = {
${tableEntries}
};

#ifdef __cplusplus
}
#endif

#endif /* TCON_FLASH_MAP_H */
`;
  }

  /**
   * Generate Keil MDK Scatter Loading description file (.sct)
   */
  static generateKeilScatter(map: FlashMemoryMap): string {
    const bootSeg = map.segments.find(s => s.type === 'bootloader') || map.segments[0];
    const fwSeg = map.segments.find(s => s.type === 'firmware') || map.segments[1] || map.segments[0];

    const bootStart = bootSeg ? `0x${bootSeg.startAddress.toString(16).toUpperCase()}` : '0x00000000';
    const bootSize = bootSeg ? `0x${bootSeg.size.toString(16).toUpperCase()}` : '0x00004000';
    const fwStart = fwSeg ? `0x${fwSeg.startAddress.toString(16).toUpperCase()}` : '0x00004000';
    const fwSize = fwSeg ? `0x${fwSeg.size.toString(16).toUpperCase()}` : '0x00040000';

    return `; *************************************************************
; *** Keil MDK Scatter Loading Description File for ${map.chipName} ***
; *** Target: ARM Cortex-M0 (Little Endian)                         ***
; *************************************************************

LR_IROM_BOOT ${bootStart} ${bootSize}  {    ; Bootloader Load Region
  ER_IROM_BOOT ${bootStart} ${bootSize}  {  ; Execution Region
   *.o (RESET, +First)
   *(InRoot$$Sections)
   .ANY (+RO)
  }
}

LR_IROM_APP ${fwStart} ${fwSize}  {      ; Main Application Load Region
  ER_IROM_APP ${fwStart} ${fwSize}  {
   *.o (APP_VECTORS, +First)
   .ANY (+RO, +XO)
  }
  RW_IRAM1 0x20000000 0x00008000  {  ; Internal SRAM 32KB
   .ANY (+RW +ZI)
  }
}
`;
  }

  /**
   * Generate GNU GCC Linker Script (.ld)
   */
  static generateGCCLinker(map: FlashMemoryMap): string {
    const totalSizeHex = `0x${map.totalCapacity.toString(16).toUpperCase()}`;

    const memoryRegions = map.segments.map(seg => {
      const name = seg.name.toUpperCase().replace(/[^A-Z0-9_]/g, '_');
      const start = `0x${seg.startAddress.toString(16).toUpperCase()}`;
      const size = `0x${seg.size.toString(16).toUpperCase()}`;
      const attr = seg.access === 'RO' || seg.access === 'EXEC' ? 'rx' : 'rw';
      return `  ${name.padEnd(20, ' ')} (${attr}) : ORIGIN = ${start}, LENGTH = ${size}`;
    }).join('\n');

    return `/* *************************************************************
 * GNU GCC Linker Script for ${map.chipName} (${map.chipFamily})
 * Total Flash: ${map.totalCapacity / 1024} KB
 * *************************************************************/

ENTRY(Reset_Handler)

MEMORY
{
${memoryRegions}
  RAM                  (xrw) : ORIGIN = 0x20000000, LENGTH = 32K
}

SECTIONS
{
  /* The startup code into first Flash segment */
  .isr_vector :
  {
    . = ALIGN(4);
    KEEP(*(.isr_vector))
    . = ALIGN(4);
  } > ${map.segments[0]?.name.toUpperCase().replace(/[^A-Z0-9_]/g, '_') || 'FLASH'}

  .text :
  {
    . = ALIGN(4);
    *(.text)
    *(.text*)
    *(.rodata)
    *(.rodata*)
    . = ALIGN(4);
    _etext = .;
  } > ${map.segments[0]?.name.toUpperCase().replace(/[^A-Z0-9_]/g, '_') || 'FLASH'}

  .data :
  {
    . = ALIGN(4);
    _sdata = .;
    *(.data)
    *(.data*)
    . = ALIGN(4);
    _edata = .;
  } > RAM AT > ${map.segments[0]?.name.toUpperCase().replace(/[^A-Z0-9_]/g, '_') || 'FLASH'}

  .bss :
  {
    . = ALIGN(4);
    _sbss = .;
    *(.bss)
    *(.bss*)
    *(COMMON)
    . = ALIGN(4);
    _ebss = .;
  } > RAM
}
`;
  }

  /**
   * Generate ARM CMSIS Core Standard Peripheral Register Header
   * Conforms to ARM Cortex-M0 CMSIS standard conventions (__I, __O, __IO, struct mapping, Pos, Msk)
   */
  static generateCMSISHeader(map: FlashMemoryMap): string {
    const timestamp = new Date().toISOString();
    const cleanChip = map.chipName.toUpperCase().replace(/[^A-Z0-9_]/g, '_');

    const regionsCode = map.registerRegions.map(region => {
      const cleanRegion = region.name.toUpperCase().replace(/[^A-Z0-9_]/g, '_');
      const sortedRegs = [...region.registers].sort((a, b) => a.relativeOffset - b.relativeOffset);

      // Construct struct members with padding for gaps
      const structMembers: string[] = [];
      let expectedOffset = 0;
      let reservedCounter = 0;

      for (const reg of sortedRegs) {
        if (reg.relativeOffset > expectedOffset) {
          const gapBytes = reg.relativeOffset - expectedOffset;
          const gapWords = Math.floor(gapBytes / 4);
          if (gapWords === 1) {
            structMembers.push(`  __I  uint32_t RESERVED${reservedCounter++};                              /*!< Offset: 0x${expectedOffset.toString(16).toUpperCase().padStart(4, '0')} Reserved */`);
          } else if (gapWords > 1) {
            structMembers.push(`  __I  uint32_t RESERVED${reservedCounter++}[${gapWords}];                           /*!< Offset: 0x${expectedOffset.toString(16).toUpperCase().padStart(4, '0')} Reserved */`);
          }
          expectedOffset = reg.relativeOffset;
        }

        const cleanReg = reg.name.toUpperCase().replace(/[^A-Z0-9_]/g, '_');
        const ioQual = '  __IO';
        const offsetHex = '0x' + reg.relativeOffset.toString(16).toUpperCase().padStart(4, '0');
        const desc = reg.description ? ` /*!< Offset: ${offsetHex} ${reg.description} */` : ` /*!< Offset: ${offsetHex} */`;
        structMembers.push(`${ioQual} uint32_t ${cleanReg};${desc}`);
        expectedOffset = reg.relativeOffset + (reg.sizeBytes || 4);
      }

      // Bitfield macros
      const bitfieldMacros: string[] = [];
      for (const reg of sortedRegs) {
        const cleanReg = reg.name.toUpperCase().replace(/[^A-Z0-9_]/g, '_');
        for (const bf of reg.bitFields) {
          const cleanField = bf.name.toUpperCase().replace(/[^A-Z0-9_]/g, '_');
          const bitWidth = bf.endBit - bf.startBit + 1;
          const maskVal = ((1 << bitWidth) - 1) >>> 0;
          const prefix = `${cleanRegion}_${cleanReg}_${cleanField}`;

          bitfieldMacros.push(
            `#define ${prefix}_Pos                    (${bf.startBit}U)`,
            `#define ${prefix}_Msk                    (0x${maskVal.toString(16).toUpperCase()}UL << ${prefix}_Pos)`,
            `#define ${prefix}                        ${prefix}_Msk`
          );
        }
      }

      return `/* ============================================================================
 * ${region.name} Subsystem (${region.registers.length} Registers)
 * Base Address: 0x${region.baseOffset.toString(16).toUpperCase().padStart(8, '0')}
 * ============================================================================ */

typedef struct {
${structMembers.join('\n')}
} ${cleanRegion}_TypeDef;

#define ${cleanRegion}_BASE                      (0x${region.baseOffset.toString(16).toUpperCase().padStart(8, '0')}UL)
#define ${cleanRegion}                           ((${cleanRegion}_TypeDef *) ${cleanRegion}_BASE)

/* Bitfield Definitions for ${cleanRegion} */
${bitfieldMacros.join('\n')}
`;
    }).join('\n\n');

    return `/**
 * ============================================================================
 * @file    ${map.chipName.toLowerCase()}_cmsis.h
 * @brief   ARM Cortex-M0 CMSIS Core Standard Peripheral Access Header
 * @chip    ${map.chipName} (${map.chipFamily})
 * @date    ${timestamp}
 * @note    GENERATED BY TLiFlashManager - CONFORMS TO ARM CMSIS-CORE 5.x
 * ============================================================================
 */

#ifndef __${cleanChip}_CMSIS_H
#define __${cleanChip}_CMSIS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Standard CMSIS Access Qualifiers */
#ifndef __I
  #define __I     volatile const    /*!< Defines 'read only' permissions */
#endif
#ifndef __O
  #define __O     volatile          /*!< Defines 'write only' permissions */
#endif
#ifndef __IO
  #define __IO    volatile          /*!< Defines 'read / write' permissions */
#endif

${regionsCode}

#ifdef __cplusplus
}
#endif

#endif /* __${cleanChip}_CMSIS_H */
`;
  }
}

